typer_assistant:
  assistant_name: Ada
  human_companion_name: Dan
  elevenlabs_voice: WejK3H1m7MI9CHnIjW9K
base_assistant:
  assistant_name: Ada
  human_companion_name: Dan
  voice: elevenlabs # local, realtime-tts, elevenlabs
  ears: realtime-stt
  brain: deepseek-v3
  elevenlabs_voice: WejK3H1m7MI9CHnIjW9K