typer_assistant:
  assistant_name: Ada
  human_companion_name: Dan
  ears: realtime-stt
  brain: deepseek-v3
  voice: elevenlabs # local, realtime-stt, elevenlabs
  elevenlabs_voice: WejK3H1m7MI9CHnIjW9K
base_assistant:
  assistant_name: Ada
  human_companion_name: Dan
  ears: realtime-stt
  brain: ollama:falcon3:10b # deepseek-v3, ollama:phi4
  voice: local # local, realtime-tts, elevenlabs
  elevenlabs_voice: WejK3H1m7MI9CHnIjW9K